//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPart
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BasedEntities : DbContext
    {
        public BasedEntities()
            : base("name=BasedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Pc> Pcs { get; set; }
        public virtual DbSet<PcDrive> PcDrives { get; set; }
        public virtual DbSet<PcGeneralInfo> PcGeneralInfoes { get; set; }
        public virtual DbSet<PcGroup> PcGroups { get; set; }
        public virtual DbSet<PcLoadInfo> PcLoadInfoes { get; set; }
    }
}
