//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PcDrive
    {
        public int id { get; set; }
        public int PcID { get; set; }
        public string Drive { get; set; }
        public string DriveType { get; set; }
        public string FileSystem { get; set; }
        public int AvailabeSpace { get; set; }
        public int TotalSize { get; set; }
    
        public virtual Pc Pc { get; set; }
    }
}
