//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PcGeneralInfo
    {
        public int PcID { get; set; }
        public string Cpu { get; set; }
        public short Cores { get; set; }
        public short LogicalProcessors { get; set; }
        public string Socket { get; set; }
        public short Ram { get; set; }
        public string SystemName { get; set; }
        public string OsArchitecture { get; set; }
        public string OsVersion { get; set; }
    
        public virtual Pc Pc { get; set; }
    }
}
