//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PcLoadInfo
    {
        public int PcID { get; set; }
        public int CpuLoad { get; set; }
        public string CpuLoadByCore { get; set; }
        public int RamLoad { get; set; }
    
        public virtual Pc Pc { get; set; }
    }
}
